data:
  input_path: "../data/joined_table.csv"

pipeline:
  target: "not_renewed_2yrs_y"
  test_train:
    split_column: "DATE ISSUED"
    splits:
      - name: exists as of 12/31/2017
        train:
          start: 01/01/2002
          end:   12/31/2017
        test:
          start: 01/01/2018
          end:   12/31/2019
  

models:
  DecisionTreeClassifier:
    max_depth: [null, 1, 5]

k: 1

num_tracts: 10
