data:
  input_path: "../data/small-input.csv"
  # input_path: "../data/joined_table100.csv"

description: "cmm-eval-test"

pipeline:
  target: "not_renewed_2yrs_y"
  test_train:
    split_column: "DATE ISSUED"
    splits:
      - name: exists as of 12/31/2008
        train:
          start: 01/01/2002
          end:   12/31/2004
        test:
          start: 01/01/2002
          end:   12/31/2006
      - name: exists as of 12/31/2010
        train:
          start: 01/01/2002
          end:   12/31/2006
        test:
          start: 01/01/2002
          end:   12/31/2008
      - name: exists as of 12/31/2012
        train:
          start: 01/01/2002
          end:   12/31/2008
        test:
          start: 01/01/2002
          end:   12/31/2010
      - name: exists as of 12/31/2014
        train:
          start: 01/01/2002
          end:   12/31/2010
        test:
          start: 01/01/2002
          end:   12/31/2012
      - name: exists as of 12/31/2016
        train:
          start: 01/01/2002
          end:   12/31/2012
        test:
          start: 01/01/2002
          end:   12/31/2014
      - name: exists as of 12/31/2018
        train:
          start: 01/01/2002
          end:   12/31/2014
        test:
          start: 01/01/2002
          end:   12/31/2016


models:
  LogisticRegression:
    C: [0.01]
    # penalty: ["l1", "l2"]

  # KNeighborsClassifier:
  #   n_neighbors: [10, 50, 100]

  DecisionTreeClassifier:
    max_depth: [null, 1, 5]

  # GradientBoostingClassifier:
  #   learning_rate: [0.1, 0.5]

  # BaggingClassifier:
  #   max_samples: [0.1, 0.5]

  # RandomForestClassifier: {}
