Starting pipeline quick-pipeline-lr-only-cmm-test (4a787757-f81f-4078-8009-142574711706) at 2019-06-02 19:49:16.436060
Input data: /Users/satej/Documents/workspace/classwork/machine-learning/chicago-business-viability/data/joined_table100.csv (SHA-256: d899ab69dc405b5079b23775938b2ed85d46fd4d002c83c8eb70e54442df1249)
Pipeline library version: 4666d15

Pipeline settings:
    summarize: False
    data_preprocessors: None
    feature_generators: [<function count_by_zip_year at 0x12ec0c7b8>, <function count_by_dist_radius at 0x12ec0c840>]
    models: {'LogisticRegression': {'C': [0.01]}}
    name: quick-pipeline-lr-only-cmm-test
    output_root_dir: /Users/satej/Documents/workspace/classwork/machine-learning/chicago-business-viability/code/output

Loading data

Running transformations for cleaning
    Applying transformation (1/2): convert-LICENSE TERM EXPIRATION DATE-to-datetime 
    LICENSE TERM EXPIRATION DATE -> LICENSE TERM EXPIRATION DATE
    Applying transformation (2/2): convert-DATE ISSUED-to-datetime 
    DATE ISSUED -> DATE ISSUED

Using entire dataset for training and testing.
Columns: Index(['Unnamed: 0', 'ID', 'LICENSE ID', 'ACCOUNT NUMBER', 'SITE NUMBER',
       'LEGAL NAME', 'DOING BUSINESS AS NAME', 'ADDRESS', 'CITY', 'STATE',
       'ZIP CODE', 'WARD', 'PRECINCT', 'WARD PRECINCT', 'POLICE DISTRICT',
       'LICENSE CODE', 'LICENSE DESCRIPTION', 'BUSINESS ACTIVITY ID',
       'BUSINESS ACTIVITY', 'LICENSE NUMBER', 'APPLICATION TYPE',
       'APPLICATION CREATED DATE', 'APPLICATION REQUIREMENTS COMPLETE',
       'PAYMENT DATE', 'CONDITIONAL APPROVAL', 'LICENSE TERM START DATE',
       'LICENSE TERM EXPIRATION DATE', 'LICENSE APPROVED FOR ISSUANCE',
       'DATE ISSUED', 'LICENSE STATUS', 'LICENSE STATUS CHANGE DATE', 'SSA',
       'LATITUDE', 'LONGITUDE', 'LOCATION', 'YEAR', 'Unnamed: 0.1',
       'which_ssa', 'in_ssa', 'num_sites', 'num_renewals'],
      dtype='object')
    Creating features on test-train set 1
