Starting pipeline test_pipeline (a5fc42d0-6b44-46cc-ba30-c2dcf6bdb89c) at 2019-05-24 16:08:01.801249
Input data: /Users/satej/Documents/workspace/classwork/machine-learning/chicago-business-viability/data/test_pipeline_data.csv (SHA-256: 1804aecf388d8a7c1feee83b60b17c8aedab4941ba383a14019e83896172a468)
Pipeline library version: e3ef098

Pipeline settings:
    summarize: False
    data_preprocessors: None
    feature_generators: None
    models: {'LogisticRegression-C0.01-penaltyl1': LogisticRegression(C=0.01, class_weight=None, dual=False, fit_intercept=True,
          intercept_scaling=1, max_iter=100, multi_class='warn',
          n_jobs=None, penalty='l1', random_state=None, solver='warn',
          tol=0.0001, verbose=0, warm_start=False), 'LogisticRegression-C0.01-penaltyl2': LogisticRegression(C=0.01, class_weight=None, dual=False, fit_intercept=True,
          intercept_scaling=1, max_iter=100, multi_class='warn',
          n_jobs=None, penalty='l2', random_state=None, solver='warn',
          tol=0.0001, verbose=0, warm_start=False), 'LogisticRegression-C0.1-penaltyl1': LogisticRegression(C=0.1, class_weight=None, dual=False, fit_intercept=True,
          intercept_scaling=1, max_iter=100, multi_class='warn',
          n_jobs=None, penalty='l1', random_state=None, solver='warn',
          tol=0.0001, verbose=0, warm_start=False), 'LogisticRegression-C0.1-penaltyl2': LogisticRegression(C=0.1, class_weight=None, dual=False, fit_intercept=True,
          intercept_scaling=1, max_iter=100, multi_class='warn',
          n_jobs=None, penalty='l2', random_state=None, solver='warn',
          tol=0.0001, verbose=0, warm_start=False), 'LogisticRegression-C1-penaltyl1': LogisticRegression(C=1, class_weight=None, dual=False, fit_intercept=True,
          intercept_scaling=1, max_iter=100, multi_class='warn',
          n_jobs=None, penalty='l1', random_state=None, solver='warn',
          tol=0.0001, verbose=0, warm_start=False), 'LogisticRegression-C1-penaltyl2': LogisticRegression(C=1, class_weight=None, dual=False, fit_intercept=True,
          intercept_scaling=1, max_iter=100, multi_class='warn',
          n_jobs=None, penalty='l2', random_state=None, solver='warn',
          tol=0.0001, verbose=0, warm_start=False), 'LogisticRegression-C10-penaltyl1': LogisticRegression(C=10, class_weight=None, dual=False, fit_intercept=True,
          intercept_scaling=1, max_iter=100, multi_class='warn',
          n_jobs=None, penalty='l1', random_state=None, solver='warn',
          tol=0.0001, verbose=0, warm_start=False), 'LogisticRegression-C10-penaltyl2': LogisticRegression(C=10, class_weight=None, dual=False, fit_intercept=True,
          intercept_scaling=1, max_iter=100, multi_class='warn',
          n_jobs=None, penalty='l2', random_state=None, solver='warn',
          tol=0.0001, verbose=0, warm_start=False), 'LogisticRegression-C100-penaltyl1': LogisticRegression(C=100, class_weight=None, dual=False, fit_intercept=True,
          intercept_scaling=1, max_iter=100, multi_class='warn',
          n_jobs=None, penalty='l1', random_state=None, solver='warn',
          tol=0.0001, verbose=0, warm_start=False), 'LogisticRegression-C100-penaltyl2': LogisticRegression(C=100, class_weight=None, dual=False, fit_intercept=True,
          intercept_scaling=1, max_iter=100, multi_class='warn',
          n_jobs=None, penalty='l2', random_state=None, solver='warn',
          tol=0.0001, verbose=0, warm_start=False), 'KNeighborsClassifier-n_neighbors1': KNeighborsClassifier(algorithm='auto', leaf_size=30, metric='minkowski',
           metric_params=None, n_jobs=None, n_neighbors=1, p=2,
           weights='uniform'), 'KNeighborsClassifier-n_neighbors10': KNeighborsClassifier(algorithm='auto', leaf_size=30, metric='minkowski',
           metric_params=None, n_jobs=None, n_neighbors=10, p=2,
           weights='uniform'), 'KNeighborsClassifier-n_neighbors25': KNeighborsClassifier(algorithm='auto', leaf_size=30, metric='minkowski',
           metric_params=None, n_jobs=None, n_neighbors=25, p=2,
           weights='uniform'), 'DecisionTreeClassifier-max_depthNone': DecisionTreeClassifier(class_weight=None, criterion='gini', max_depth=None,
            max_features=None, max_leaf_nodes=None,
            min_impurity_decrease=0.0, min_impurity_split=None,
            min_samples_leaf=1, min_samples_split=2,
            min_weight_fraction_leaf=0.0, presort=False, random_state=None,
            splitter='best'), 'DecisionTreeClassifier-max_depth5': DecisionTreeClassifier(class_weight=None, criterion='gini', max_depth=5,
            max_features=None, max_leaf_nodes=None,
            min_impurity_decrease=0.0, min_impurity_split=None,
            min_samples_leaf=1, min_samples_split=2,
            min_weight_fraction_leaf=0.0, presort=False, random_state=None,
            splitter='best'), 'DecisionTreeClassifier-max_depth10': DecisionTreeClassifier(class_weight=None, criterion='gini', max_depth=10,
            max_features=None, max_leaf_nodes=None,
            min_impurity_decrease=0.0, min_impurity_split=None,
            min_samples_leaf=1, min_samples_split=2,
            min_weight_fraction_leaf=0.0, presort=False, random_state=None,
            splitter='best'), 'DecisionTreeClassifier-max_depth100': DecisionTreeClassifier(class_weight=None, criterion='gini', max_depth=100,
            max_features=None, max_leaf_nodes=None,
            min_impurity_decrease=0.0, min_impurity_split=None,
            min_samples_leaf=1, min_samples_split=2,
            min_weight_fraction_leaf=0.0, presort=False, random_state=None,
            splitter='best'), 'GradientBoostingClassifier-learning_rate0.1': GradientBoostingClassifier(criterion='friedman_mse', init=None,
              learning_rate=0.1, loss='deviance', max_depth=3,
              max_features=None, max_leaf_nodes=None,
              min_impurity_decrease=0.0, min_impurity_split=None,
              min_samples_leaf=1, min_samples_split=2,
              min_weight_fraction_leaf=0.0, n_estimators=100,
              n_iter_no_change=None, presort='auto', random_state=None,
              subsample=1.0, tol=0.0001, validation_fraction=0.1,
              verbose=0, warm_start=False), 'GradientBoostingClassifier-learning_rate0.5': GradientBoostingClassifier(criterion='friedman_mse', init=None,
              learning_rate=0.5, loss='deviance', max_depth=3,
              max_features=None, max_leaf_nodes=None,
              min_impurity_decrease=0.0, min_impurity_split=None,
              min_samples_leaf=1, min_samples_split=2,
              min_weight_fraction_leaf=0.0, n_estimators=100,
              n_iter_no_change=None, presort='auto', random_state=None,
              subsample=1.0, tol=0.0001, validation_fraction=0.1,
              verbose=0, warm_start=False), 'GradientBoostingClassifier-learning_rate2.0': GradientBoostingClassifier(criterion='friedman_mse', init=None,
              learning_rate=2.0, loss='deviance', max_depth=3,
              max_features=None, max_leaf_nodes=None,
              min_impurity_decrease=0.0, min_impurity_split=None,
              min_samples_leaf=1, min_samples_split=2,
              min_weight_fraction_leaf=0.0, n_estimators=100,
              n_iter_no_change=None, presort='auto', random_state=None,
              subsample=1.0, tol=0.0001, validation_fraction=0.1,
              verbose=0, warm_start=False), 'BaggingClassifier-max_samples0.1': BaggingClassifier(base_estimator=None, bootstrap=True,
         bootstrap_features=False, max_features=1.0, max_samples=0.1,
         n_estimators=10, n_jobs=None, oob_score=False, random_state=None,
         verbose=0, warm_start=False), 'BaggingClassifier-max_samples0.5': BaggingClassifier(base_estimator=None, bootstrap=True,
         bootstrap_features=False, max_features=1.0, max_samples=0.5,
         n_estimators=10, n_jobs=None, oob_score=False, random_state=None,
         verbose=0, warm_start=False), 'BaggingClassifier-max_samples1.0': BaggingClassifier(base_estimator=None, bootstrap=True,
         bootstrap_features=False, max_features=1.0, max_samples=1.0,
         n_estimators=10, n_jobs=None, oob_score=False, random_state=None,
         verbose=0, warm_start=False), 'RandomForestClassifier': RandomForestClassifier(bootstrap=True, class_weight=None, criterion='gini',
            max_depth=None, max_features='auto', max_leaf_nodes=None,
            min_impurity_decrease=0.0, min_impurity_split=None,
            min_samples_leaf=1, min_samples_split=2,
            min_weight_fraction_leaf=0.0, n_estimators='warn', n_jobs=None,
            oob_score=False, random_state=None, verbose=0,
            warm_start=False)}
    name: test_pipeline
    output_root_dir: /Users/satej/Documents/workspace/classwork/machine-learning/chicago-business-viability/code/output

Loading data
Columns: Index(['Unnamed: 0', 'sepal length', 'sepal width', 'petal length',
       'petal width', 'target'],
      dtype='object')
Training models.
Features: ['sepal length', 'sepal width', 'petal length', 'petal width']
Fitting: target
    Training model LogisticRegression-C0.01-penaltyl1
        Training on training set (1/1)
    Training model LogisticRegression-C0.01-penaltyl2
        Training on training set (1/1)
    Training model LogisticRegression-C0.1-penaltyl1
        Training on training set (1/1)
    Training model LogisticRegression-C0.1-penaltyl2
        Training on training set (1/1)
    Training model LogisticRegression-C1-penaltyl1
        Training on training set (1/1)
    Training model LogisticRegression-C1-penaltyl2
        Training on training set (1/1)
    Training model LogisticRegression-C10-penaltyl1
        Training on training set (1/1)
    Training model LogisticRegression-C10-penaltyl2
        Training on training set (1/1)
    Training model LogisticRegression-C100-penaltyl1
        Training on training set (1/1)
    Training model LogisticRegression-C100-penaltyl2
        Training on training set (1/1)
    Training model KNeighborsClassifier-n_neighbors1
        Training on training set (1/1)
    Training model KNeighborsClassifier-n_neighbors10
        Training on training set (1/1)
    Training model KNeighborsClassifier-n_neighbors25
        Training on training set (1/1)
    Training model DecisionTreeClassifier-max_depthNone
        Training on training set (1/1)
    Training model DecisionTreeClassifier-max_depth5
        Training on training set (1/1)
    Training model DecisionTreeClassifier-max_depth10
        Training on training set (1/1)
    Training model DecisionTreeClassifier-max_depth100
        Training on training set (1/1)
    Training model GradientBoostingClassifier-learning_rate0.1
        Training on training set (1/1)
    Training model GradientBoostingClassifier-learning_rate0.5
        Training on training set (1/1)
    Training model GradientBoostingClassifier-learning_rate2.0
        Training on training set (1/1)
    Training model BaggingClassifier-max_samples0.1
        Training on training set (1/1)
    Training model BaggingClassifier-max_samples0.5
        Training on training set (1/1)
    Training model BaggingClassifier-max_samples1.0
        Training on training set (1/1)
    Training model RandomForestClassifier
        Training on training set (1/1)
Testing models.
    Evaluating model LogisticRegression-C0.01-penaltyl1
        Evaluating on testing set (1/1)
    Model score: 0.6666666666666666
    Evaluating model LogisticRegression-C0.01-penaltyl2
        Evaluating on testing set (1/1)
    Model score: 0.8866666666666667
    Evaluating model LogisticRegression-C0.1-penaltyl1
        Evaluating on testing set (1/1)
    Model score: 0.9466666666666667
    Evaluating model LogisticRegression-C0.1-penaltyl2
        Evaluating on testing set (1/1)
    Model score: 0.9733333333333334
    Evaluating model LogisticRegression-C1-penaltyl1
        Evaluating on testing set (1/1)
    Model score: 0.9666666666666667
    Evaluating model LogisticRegression-C1-penaltyl2
        Evaluating on testing set (1/1)
    Model score: 0.98
    Evaluating model LogisticRegression-C10-penaltyl1
        Evaluating on testing set (1/1)
    Model score: 0.98
    Evaluating model LogisticRegression-C10-penaltyl2
        Evaluating on testing set (1/1)
    Model score: 0.98
    Evaluating model LogisticRegression-C100-penaltyl1
        Evaluating on testing set (1/1)
    Model score: 0.9866666666666667
    Evaluating model LogisticRegression-C100-penaltyl2
        Evaluating on testing set (1/1)
    Model score: 0.98
    Evaluating model KNeighborsClassifier-n_neighbors1
        Evaluating on testing set (1/1)
    Model score: 1.0
    Evaluating model KNeighborsClassifier-n_neighbors10
        Evaluating on testing set (1/1)
    Model score: 0.98
    Evaluating model KNeighborsClassifier-n_neighbors25
        Evaluating on testing set (1/1)
    Model score: 0.98
    Evaluating model DecisionTreeClassifier-max_depthNone
        Evaluating on testing set (1/1)
    Model score: 1.0
    Evaluating model DecisionTreeClassifier-max_depth5
        Evaluating on testing set (1/1)
    Model score: 1.0
    Evaluating model DecisionTreeClassifier-max_depth10
        Evaluating on testing set (1/1)
    Model score: 1.0
    Evaluating model DecisionTreeClassifier-max_depth100
        Evaluating on testing set (1/1)
    Model score: 1.0
    Evaluating model GradientBoostingClassifier-learning_rate0.1
        Evaluating on testing set (1/1)
    Model score: 1.0
    Evaluating model GradientBoostingClassifier-learning_rate0.5
        Evaluating on testing set (1/1)
    Model score: 1.0
    Evaluating model GradientBoostingClassifier-learning_rate2.0
        Evaluating on testing set (1/1)
    Model score: 1.0
    Evaluating model BaggingClassifier-max_samples0.1
        Evaluating on testing set (1/1)
    Model score: 0.96
    Evaluating model BaggingClassifier-max_samples0.5
        Evaluating on testing set (1/1)
    Model score: 0.9866666666666667
    Evaluating model BaggingClassifier-max_samples1.0
        Evaluating on testing set (1/1)
    Model score: 0.9933333333333333
    Evaluating model RandomForestClassifier
        Evaluating on testing set (1/1)
    Model score: 1.0
Copying artifacts to stable path
