Starting pipeline quick-pipeline-lr-only-cmm-test (d20aa16e-b9b4-4967-b423-10fb2b6d9f50) at 2019-06-02 21:46:36.294962
Input data: /Users/jonathantan/github/chicago-business-viability/data/joined_table100.csv (SHA-256: d899ab69dc405b5079b23775938b2ed85d46fd4d002c83c8eb70e54442df1249)
Pipeline library version: 34fb60a

Pipeline settings:
    summarize: False
    data_preprocessors: None
    feature_generators: [<function count_by_zip_year at 0x118e2c9d8>, <function count_by_dist_radius at 0x118e2ca60>]
    models: {'LogisticRegression': {'C': [0.01]}}
    name: quick-pipeline-lr-only-cmm-test
    output_root_dir: /Users/jonathantan/github/chicago-business-viability/code/output

Loading data

Running transformations for cleaning
    Applying transformation (1/2): convert-LICENSE TERM EXPIRATION DATE-to-datetime 
    LICENSE TERM EXPIRATION DATE -> LICENSE TERM EXPIRATION DATE
    Applying transformation (2/2): convert-DATE ISSUED-to-datetime 
    DATE ISSUED -> DATE ISSUED

Using entire dataset for training and testing.
Columns: Index(['Unnamed: 0', 'ID', 'LICENSE ID', 'ACCOUNT NUMBER', 'SITE NUMBER',
       'LEGAL NAME', 'DOING BUSINESS AS NAME', 'ADDRESS', 'CITY', 'STATE',
       'ZIP CODE', 'WARD', 'PRECINCT', 'WARD PRECINCT', 'POLICE DISTRICT',
       'LICENSE CODE', 'LICENSE DESCRIPTION', 'BUSINESS ACTIVITY ID',
       'BUSINESS ACTIVITY', 'LICENSE NUMBER', 'APPLICATION TYPE',
       'APPLICATION CREATED DATE', 'APPLICATION REQUIREMENTS COMPLETE',
       'PAYMENT DATE', 'CONDITIONAL APPROVAL', 'LICENSE TERM START DATE',
       'LICENSE TERM EXPIRATION DATE', 'LICENSE APPROVED FOR ISSUANCE',
       'DATE ISSUED', 'LICENSE STATUS', 'LICENSE STATUS CHANGE DATE', 'SSA',
       'LATITUDE', 'LONGITUDE', 'LOCATION', 'YEAR', 'Unnamed: 0.1',
       'which_ssa', 'in_ssa', 'num_sites', 'num_renewals'],
      dtype='object')
    Creating features on test-train set 1
    Creating features on test-train set 1
    Balancing features for test-train set 1
Training models.
Features: []
Fitting: not_renewed_2yrs
